"""Column definitions shared by every model, so the same idea is spelled the same way."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from uuid import UUID

from sqlalchemy import DateTime, Enum, Uuid, func
from sqlalchemy.orm import Mapped, MappedColumn, mapped_column


def uuid_primary_key() -> MappedColumn[UUID]:
    """Primary key generated by the database, as in the supplied base schema."""
    return mapped_column(Uuid, primary_key=True, server_default=func.gen_random_uuid())


def enum_column(enum: type[StrEnum], *, default: StrEnum | None = None) -> MappedColumn[StrEnum]:
    """A status column stored as its text value rather than its member name.

    The CHECK constraint that restricts the allowed values lives in the migration,
    which is the single source of truth for the schema.
    """
    return mapped_column(
        Enum(
            enum,
            native_enum=False,
            create_constraint=False,
            values_callable=lambda members: [member.value for member in members],
        ),
        nullable=False,
        server_default=default.value if default is not None else None,
    )


class CreatedAtMixin:
    """For rows that are written once and never changed."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class TimestampMixin(CreatedAtMixin):
    """For rows that are updated after creation."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
